version: 0.2
phases:
  install:
    commands:
      - REPOSITORY_URI=872599169723.dkr.ecr.ap-south-1.amazonaws.com/canary
  pre_build:
    commands:
      - echo Logging starting build ...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 918462768359.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the nginx  Docker image...          
      - docker build -t $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER > imageDetail.json
artifacts:
  files: 
    - 'imagedefinitions.json'
    - 'appspec.yaml'
    - 'taskdef.json'
    - 'imageDetail.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
